version: '2'
services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:latest
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        ## GitLab configuration settings
        ##! Check out the latest version of this file to know about the different
        ##! settings that can be configured by this file, which may be found at:
        ##! https://gitlab.com/gitlab-org/omnibus-gitlab/raw/master/files/gitlab-config-template/gitlab.rb.template

        ## GitLab URL
        ##! URL on which GitLab will be reachable.
        ##! For more details on configuring external_url see:
        ##! https://docs.gitlab.com/omnibus/settings/configuration.html#configuring-the-external-url-for-gitlab
        external_url 'http://gitlab.home'

        ################################################################################
        ## gitlab.yml configuration
        ##! Docs: https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/doc/settings/gitlab.yml.md
        ################################################################################

        gitlab_rails['gitlab_ssh_host'] = 'gitlab.home'
        gitlab_rails['time_zone'] = 'UTC'

        ################################################################################
        ## Container Registry settings
        ##! Docs: https://docs.gitlab.com/ce/administration/container_registry.html
        ################################################################################

        registry_external_url 'http://gitlab.home'

        ################################################################################
        ## GitLab Pages
        ##! Docs: https://docs.gitlab.com/ce/pages/administration.html
        ################################################################################

        pages_external_url 'http://.gitlab.home/'

        ################################################################################
        ## GitLab Mattermost
        ##! Docs: https://docs.gitlab.com/omnibus/gitlab-mattermost
        ################################################################################

        mattermost_external_url 'http://gitlab.home'
    volumes_from:
      - gitlab-data
    ports:
      - "80:80"
      - "2222:22"

  gitlab-data:
    container_name: gitlab-data
    image: busybox
    volumes:
      - /etc/gitlab
      - /var/log/gitlab
      - /var/opt/gitlab

  gitlab-runner:
    container_name: gitlab-runner
    image: gitlab/gitlab-runner:alpine
    restart: always
    volumes_from:
      - gitlab-runner-data
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$HOME/.docker/config.json:/root/.docker/config.json"

  gitlab-runner-data:
    container_name: gitlab-runner-data
    image: busybox
    volumes:
      - /etc/gitlab-runner
